# Generated by Django 2.0.5 on 2018-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180527_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
