# Generated by Django 2.0.5 on 2018-06-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180527_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rgb', models.CharField(max_length=6)),
                ('is_trans', models.BooleanField()),
            ],
        ),
    ]
