# Generated by Django 2.0.5 on 2018-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180610_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
