# Generated by Django 2.0.5 on 2018-06-10 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20180610_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_display', models.IntegerField(default=0)),
                ('quantity_in_storage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Color'),
        ),
        migrations.AlterField(
            model_name='element',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Part'),
        ),
        migrations.AddField(
            model_name='userelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Element'),
        ),
        migrations.AddField(
            model_name='userelement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
