# Generated by Django 2.0.5 on 2018-07-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180612_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='meta',
            field=models.BooleanField(default=0),
        ),
    ]
