# Generated by Django 2.0.5 on 2018-07-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_part_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_num', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.SmallIntegerField()),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SetTheme')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SetTheme'),
        ),
    ]
