# Generated by Django 2.0.5 on 2018-07-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180711_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settheme',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SetTheme'),
        ),
    ]
