# Generated by Django 2.0.5 on 2018-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180713_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
